In [119]:
#Punto 1: Literal A
import numpy as np
def funcion1(A,B,C,D): #Se definen las entradas de la funcion
  valor = np.linalg.matrix_power(A,C)@np.linalg.matrix_power(B,D) #Se calcula el producto punto y las potencias
  return valor
np.random.seed(0) #Se define una semilla para los valores aleatorios
A = np.random.rand(2,2) #Se genera la matriz A
B = np.random.rand(2,2) #Se genera la matriz B
C = 2 #Se define el exponente que eleva a A
D = 2 #Se define el exponente que eleva a B
resultado = funcion1(A,B,C,D) #Se obtiene el resultado a traves de la funcion
print(resultado) #Se imprime el resultado final

[[0.78864864 1.46529921]
 [0.72368723 1.34480199]]


In [120]:
#Punto 1: Literal B
def funcion2(A,B,C,D): #Se definen las entradas de la funcion
  dim1 = np.shape(A) #Se obtienen las dimensiones de A
  dim2 = np.shape(B) #Se obtienen las dimensiones de B
  if (dim1[1] == dim2[0] and dim1[0]==dim1[1] and dim2[0]==dim2[1]): #Si se cumple que el numero de columnas de A es igual al numero de filas de B y ambas matrices son cuadradas se realiza la multiplicacion
    valor = np.linalg.matrix_power(A,C)@np.linalg.matrix_power(B,D)
  elif (dim1[1] == dim2[0] and C==1 and D==1): #Si se cumple que el numero de columnas de A es igual al numero de filas de B y la matriz A y B no son cuadradas pero tienen exponente 1 se realiza la multiplicacion
    valor = A@B
  elif (dim1[1] == dim2[0] and C==1 and D!=1): #Si se cumple que el numero de columnas de A es igual al numero de filas de B y la matriz A no es cuadrada pero tiene exponente 1 se realiza la multiplicacion
    valor = A@np.linalg.matrix_power(B,D)
  elif (dim1[1] == dim2[0] and D==1 and C!=1): #Si se cumple que el numero de columnas de A es igual al numero de filas de B y la matriz B no es cuadrada pero tiene exponente 1 se realiza la multiplicacion
    valor = np.linalg.matrix_power(A,C)@B
  else: #Si no se cumple, se retorna un str
    valor = 'Las matrices no se pueden multiplicar'
  return valor 
np.random.seed(0) #Se define una semilla para los valores aleatorios
A = np.random.rand(2,3) #Se genera la matriz A
B = np.random.rand(1,2) #Se genera la matriz B
C = 1 #Se define el exponente que eleva a A
D = 1 #Se define el exponente que eleva a B
resultado = funcion2(A,B,C,D) #Se obtiene el resultado a traves de la funcion
print(resultado) #Se imprime el resultado final

Las matrices no se pueden multiplicar


In [121]:
#Punto 2: Literal A
A = np.array([[0.1, 2],[2,0.1]]) #Se genera la matriz A
B = np.array([[1, 2, 3],[4, 5, 6]]) #Se genera la matriz B
C = np.array([[5/3, 2/3],[5/3, 2/3]]) #Se genera la matriz C

valor1 = funcion2(A,B.T,1,1) #Literal 1
valor2 = funcion2(A,B,2,1)  #Literal 2
valor3 = funcion2(B,C,1,3) #Literal 3
valor4 = funcion2(B.T,C,1,4) #Literal 4
print('Resultado literal 1:')
print(valor1) #Se imprime el resultado final
print('Resultado literal 2:')
print(valor2) #Se imprime el resultado final
print('Resultado literal 3:')
print(valor3) #Se imprime el resultado final
print('Resultado literal 4:')
print(valor4) #Se imprime el resultado final

Resultado literal 1:
Las matrices no se pueden multiplicar
Resultado literal 2:
[[ 5.61 10.02 14.43]
 [16.44 20.85 25.26]]
Resultado literal 3:
Las matrices no se pueden multiplicar
Resultado literal 4:
[[105.86419753  42.34567901]
 [148.20987654  59.28395062]
 [190.55555556  76.22222222]]


In [122]:
#Punto 2: Literal B
A = np.array([[0.1, 2],[2,0.1]]) #Se genera la matriz A
B = np.array([[1, 2, 3],[4, 5, 6]]) #Se genera la matriz B
inC = int(input('Ingrese la primera potencia (C): ')) #Se solicita al usuario el valor de C
inD = int(input('Ingrese la segunda potencia (D): ')) #Se solicita al usuario el valor de D
valor1 = funcion2(A,B,inC,inD) #Se obtiene el resultado a traves de la funcion
print(valor1) #Se imprime el resultado final

Ingrese la primera potencia (C): 2
Ingrese la segunda potencia (D): 1
[[ 5.61 10.02 14.43]
 [16.44 20.85 25.26]]


In [123]:
#Punto 3
A = np.array([[3.0, 2.0, 2.0],[-2.0, 1.0, 4.0],[1.0, 0.0, 3.0],[5.0, -2.0, 1.0]]) #Se genera la matriz A
print('Matriz en estado inicial:')
print(A) #Se imprime el resultado final
A[0] = A[0]*(1/4) #Literal a
print('Literal a:')
print(A)
A[1] = A[1] + 3*A[0] #Literal b
print('Literal b:')
print(A)
A[2] = A[2] - 1*A[0] #Literal c
print('Literal c:')
print(A)
A[3] = A[3] - 5*A[0] #Literal d
print('Literal d:')
print(A)
A = A[[0,3,2,1],:] #Literal d
print('Literal e:')
print(A)


Matriz en estado inicial:
[[ 3.  2.  2.]
 [-2.  1.  4.]
 [ 1.  0.  3.]
 [ 5. -2.  1.]]
Literal a:
[[ 0.75  0.5   0.5 ]
 [-2.    1.    4.  ]
 [ 1.    0.    3.  ]
 [ 5.   -2.    1.  ]]
Literal b:
[[ 0.75  0.5   0.5 ]
 [ 0.25  2.5   5.5 ]
 [ 1.    0.    3.  ]
 [ 5.   -2.    1.  ]]
Literal c:
[[ 0.75  0.5   0.5 ]
 [ 0.25  2.5   5.5 ]
 [ 0.25 -0.5   2.5 ]
 [ 5.   -2.    1.  ]]
Literal d:
[[ 0.75  0.5   0.5 ]
 [ 0.25  2.5   5.5 ]
 [ 0.25 -0.5   2.5 ]
 [ 1.25 -4.5  -1.5 ]]
Literal e:
[[ 0.75  0.5   0.5 ]
 [ 1.25 -4.5  -1.5 ]
 [ 0.25 -0.5   2.5 ]
 [ 0.25  2.5   5.5 ]]
